{
  "model": {
    "path": "src/yolov8n-seg.pt",
    "conf": 0.3,
    "classes": [2]
  },
  "places": {
    "id_start": 1,
    "id_end": 13,
    "mask_width": 640,
    "mask_height": 384,
    "mask_thresh": 127
  },
  "car": {
    "mask_thresh": 0.5,
    "min_area": 100
  },
  "matching": {
    "car_overlap": 0.8,
    "bottom_overlap": 0.2
  }
}
